export const createMaintainReqSchema = {
  additionalProperties: false,
  type: "object",
  required: ["body"],
  properties: {
    body: {
      additionalProperties: false,
      type: "object",
      properties: {
        ticket: { type: "string", description: "关联的工单 id" },
        status: {
          type: "string",
          enum: [
            "CREATING",
            "WAITING",
            "MAINTAINING",
            "REPARING",
            "PENDING",
            "PASSED",
          ],
          description: "维保单工单状态",
        },
        rejected: { type: "boolean", description: "工单曾经被驳回" },
        crm: { type: "string", description: "CRM 订单号" },
        vehicle: { type: "string", description: "关联车辆 id" },
        terminal: { type: "string", description: "关联车辆 终端用户" },
        plate: { type: "string", description: "关联车辆 车牌号" },
        vin: { type: "string", description: "关联车辆 vin" },
        brands: { type: "string", description: "关联车辆 整车品牌" },
        appearance: { type: "string", description: "外观检查组" },
        software: { type: "string", description: "软件诊断组" },
        closeAt: {
          tsType: "Date",
          type: "string",
          format: "date-time",
          description: "完工时间",
        },
        appearanceRecord: {
          additionalProperties: false,
          type: "object",
          description: "维保单外观诊断记录",
          required: [
            "appearanceSignAddress",
            "appearanceArrivalAt",
            "appearanceWorkers",
            "meterAlarm",
            "boxDamage",
            "electricLeakage",
            "valveLoose",
            "coverAbnormal",
            "headLoose",
            "boltLoose",
            "msdAbnormal",
            "hvWireWear",
            "lvWireWear",
            "hvConnectorFasten",
            "lvConnectorFasten",
            "frontPic",
            "nameplatePic",
            "meterPic",
            "batteryPic",
          ],
          properties: {
            appearanceSignAddress: { type: "string" },
            appearanceArrivalAt: {
              tsType: "Date",
              type: "string",
              format: "date-time",
            },
            appearanceRouteMap: { type: "string" },
            appearanceWorkers: { type: "array", items: { type: "string" } },
            meterAlarm: { type: "boolean" },
            meterAlarmResult: { type: "boolean" },
            meterAlarmDesc: { type: "string" },
            boxDamage: { type: "boolean" },
            boxDamageResult: { type: "boolean" },
            boxDamageDesc: { type: "string" },
            electricLeakage: { type: "boolean" },
            electricLeakageResult: { type: "boolean" },
            electricLeakageDesc: { type: "string" },
            valveLoose: { type: "boolean" },
            valveLooseResult: { type: "boolean" },
            valveLooseDesc: { type: "string" },
            coverAbnormal: { type: "boolean" },
            coverAbnormalResult: { type: "boolean" },
            coverAbnormalDesc: { type: "string" },
            headLoose: { type: "boolean" },
            headLooseResult: { type: "boolean" },
            headLooseDesc: { type: "string" },
            boltLoose: { type: "boolean" },
            boltLooseResult: { type: "boolean" },
            boltLooseDesc: { type: "string" },
            msdAbnormal: { type: "boolean" },
            msdAbnormalResult: { type: "boolean" },
            msdAbnormalDesc: { type: "string" },
            hvWireWear: { type: "boolean" },
            hvWireWearResult: { type: "boolean" },
            hvWireWearDesc: { type: "string" },
            lvWireWear: { type: "boolean" },
            lvWireWearResult: { type: "boolean" },
            lvWireWearDesc: { type: "string" },
            hvConnectorFasten: { type: "boolean" },
            hvConnectorFastenResult: { type: "boolean" },
            hvConnectorFastenDesc: { type: "string" },
            lvConnectorFasten: { type: "boolean" },
            lvConnectorFastenResult: { type: "boolean" },
            lvConnectorFastenDesc: { type: "string" },
            frontPic: { type: "array", items: { type: "string" } },
            nameplatePic: { type: "array", items: { type: "string" } },
            meterPic: { type: "array", items: { type: "string" } },
            batteryPic: { type: "array", items: { type: "string" } },
            status: {
              type: "string",
              enum: [
                "CREATING",
                "WAITING",
                "MAINTAINING",
                "REPARING",
                "PENDING",
                "PASSED",
              ],
            },
          },
        },
        softwareRecord: {
          additionalProperties: false,
          type: "object",
          description: "维保单软件诊断记录",
          required: [
            "softwareSignAddress",
            "softwareArrivalAt",
            "softwareWorkers",
            "softwareStartPic",
            "softwareEndPic",
            "soh",
            "current",
            "soc",
            "roc",
            "addVoltage",
            "totalVoltage",
            "maxVoltage",
            "minVoltage",
            "maxTemperature",
            "minTemperature",
            "diffTemperature",
            "batteryBalance",
            "diffVoltage",
            "chargePositive",
            "chargeNegative",
            "nochargePositive",
            "nochargeNegative",
          ],
          properties: {
            softwareSignAddress: { type: "string" },
            softwareArrivalAt: {
              tsType: "Date",
              type: "string",
              format: "date-time",
            },
            softwareRouteMap: { type: "string" },
            softwareWorkers: { type: "array", items: { type: "string" } },
            softwareStartPic: { type: "array", items: { type: "string" } },
            softwareEndPic: { type: "array", items: { type: "string" } },
            soh: { type: "string" },
            sohResult: { type: "string" },
            sohDesc: { type: "string" },
            current: { type: "string" },
            currentResult: { type: "string" },
            currentDesc: { type: "string" },
            soc: { type: "string" },
            socResult: { type: "string" },
            roc: { type: "string" },
            rocResult: { type: "string" },
            socDesc: { type: "string" },
            addVoltage: { type: "string" },
            addVoltageResult: { type: "string" },
            totalVoltage: { type: "string" },
            totalVoltageResult: { type: "string" },
            addVoltageDesc: { type: "string" },
            maxVoltage: { type: "string" },
            maxVoltageResult: { type: "string" },
            maxVoltageDesc: { type: "string" },
            minVoltage: { type: "string" },
            minVoltageResult: { type: "string" },
            minVoltageDesc: { type: "string" },
            maxTemperature: { type: "string" },
            maxTemperatureResult: { type: "string" },
            maxTemperatureDesc: { type: "string" },
            minTemperature: { type: "string" },
            minTemperatureResult: { type: "string" },
            minTemperatureDesc: { type: "string" },
            diffTemperature: { type: "string" },
            diffTemperatureResult: { type: "string" },
            diffTemperatureDesc: { type: "string" },
            batteryBalance: { type: "string", enum: ["LOW", "MIDDLE", "HIGH"] },
            diffVoltage: { type: "string" },
            diffVoltageResult: { type: "string" },
            diffVoltageDesc: { type: "string" },
            chargePositive: { type: "string" },
            chargePositiveResult: { type: "string" },
            chargeNegative: { type: "string" },
            chargeNegativeResult: { type: "string" },
            chargePositiveDesc: { type: "string" },
            nochargePositive: { type: "string" },
            nochargePositiveResult: { type: "string" },
            nochargeNegative: { type: "string" },
            nochargeNegativeResult: { type: "string" },
            nochargePositiveDesc: { type: "string" },
            status: {
              type: "string",
              enum: [
                "CREATING",
                "WAITING",
                "MAINTAINING",
                "REPARING",
                "PENDING",
                "PASSED",
              ],
            },
          },
        },
        repair: { type: "string", description: "关联维修单 id" },
      },
    },
  },
};
export const createMaintainResSchema = {
  additionalProperties: false,
  type: "object",
  required: [],
  properties: {
    content: {
      allOf: [
        {
          additionalProperties: false,
          type: "object",
          properties: {
            ticket: { type: "string", description: "关联的工单 id" },
            status: {
              type: "string",
              enum: [
                "CREATING",
                "WAITING",
                "MAINTAINING",
                "REPARING",
                "PENDING",
                "PASSED",
              ],
              description: "维保单工单状态",
            },
            rejected: { type: "boolean", description: "工单曾经被驳回" },
            crm: { type: "string", description: "CRM 订单号" },
            vehicle: { type: "string", description: "关联车辆 id" },
            terminal: { type: "string", description: "关联车辆 终端用户" },
            plate: { type: "string", description: "关联车辆 车牌号" },
            vin: { type: "string", description: "关联车辆 vin" },
            brands: { type: "string", description: "关联车辆 整车品牌" },
            appearance: { type: "string", description: "外观检查组" },
            software: { type: "string", description: "软件诊断组" },
            closeAt: {
              tsType: "Date",
              type: "string",
              format: "date-time",
              description: "完工时间",
            },
            appearanceRecord: {
              additionalProperties: false,
              type: "object",
              description: "维保单外观诊断记录",
              required: [
                "appearanceSignAddress",
                "appearanceArrivalAt",
                "appearanceWorkers",
                "meterAlarm",
                "boxDamage",
                "electricLeakage",
                "valveLoose",
                "coverAbnormal",
                "headLoose",
                "boltLoose",
                "msdAbnormal",
                "hvWireWear",
                "lvWireWear",
                "hvConnectorFasten",
                "lvConnectorFasten",
                "frontPic",
                "nameplatePic",
                "meterPic",
                "batteryPic",
              ],
              properties: {
                appearanceSignAddress: { type: "string" },
                appearanceArrivalAt: {
                  tsType: "Date",
                  type: "string",
                  format: "date-time",
                },
                appearanceRouteMap: { type: "string" },
                appearanceWorkers: { type: "array", items: { type: "string" } },
                meterAlarm: { type: "boolean" },
                meterAlarmResult: { type: "boolean" },
                meterAlarmDesc: { type: "string" },
                boxDamage: { type: "boolean" },
                boxDamageResult: { type: "boolean" },
                boxDamageDesc: { type: "string" },
                electricLeakage: { type: "boolean" },
                electricLeakageResult: { type: "boolean" },
                electricLeakageDesc: { type: "string" },
                valveLoose: { type: "boolean" },
                valveLooseResult: { type: "boolean" },
                valveLooseDesc: { type: "string" },
                coverAbnormal: { type: "boolean" },
                coverAbnormalResult: { type: "boolean" },
                coverAbnormalDesc: { type: "string" },
                headLoose: { type: "boolean" },
                headLooseResult: { type: "boolean" },
                headLooseDesc: { type: "string" },
                boltLoose: { type: "boolean" },
                boltLooseResult: { type: "boolean" },
                boltLooseDesc: { type: "string" },
                msdAbnormal: { type: "boolean" },
                msdAbnormalResult: { type: "boolean" },
                msdAbnormalDesc: { type: "string" },
                hvWireWear: { type: "boolean" },
                hvWireWearResult: { type: "boolean" },
                hvWireWearDesc: { type: "string" },
                lvWireWear: { type: "boolean" },
                lvWireWearResult: { type: "boolean" },
                lvWireWearDesc: { type: "string" },
                hvConnectorFasten: { type: "boolean" },
                hvConnectorFastenResult: { type: "boolean" },
                hvConnectorFastenDesc: { type: "string" },
                lvConnectorFasten: { type: "boolean" },
                lvConnectorFastenResult: { type: "boolean" },
                lvConnectorFastenDesc: { type: "string" },
                frontPic: { type: "array", items: { type: "string" } },
                nameplatePic: { type: "array", items: { type: "string" } },
                meterPic: { type: "array", items: { type: "string" } },
                batteryPic: { type: "array", items: { type: "string" } },
                status: {
                  type: "string",
                  enum: [
                    "CREATING",
                    "WAITING",
                    "MAINTAINING",
                    "REPARING",
                    "PENDING",
                    "PASSED",
                  ],
                },
              },
            },
            softwareRecord: {
              additionalProperties: false,
              type: "object",
              description: "维保单软件诊断记录",
              required: [
                "softwareSignAddress",
                "softwareArrivalAt",
                "softwareWorkers",
                "softwareStartPic",
                "softwareEndPic",
                "soh",
                "current",
                "soc",
                "roc",
                "addVoltage",
                "totalVoltage",
                "maxVoltage",
                "minVoltage",
                "maxTemperature",
                "minTemperature",
                "diffTemperature",
                "batteryBalance",
                "diffVoltage",
                "chargePositive",
                "chargeNegative",
                "nochargePositive",
                "nochargeNegative",
              ],
              properties: {
                softwareSignAddress: { type: "string" },
                softwareArrivalAt: {
                  tsType: "Date",
                  type: "string",
                  format: "date-time",
                },
                softwareRouteMap: { type: "string" },
                softwareWorkers: { type: "array", items: { type: "string" } },
                softwareStartPic: { type: "array", items: { type: "string" } },
                softwareEndPic: { type: "array", items: { type: "string" } },
                soh: { type: "string" },
                sohResult: { type: "string" },
                sohDesc: { type: "string" },
                current: { type: "string" },
                currentResult: { type: "string" },
                currentDesc: { type: "string" },
                soc: { type: "string" },
                socResult: { type: "string" },
                roc: { type: "string" },
                rocResult: { type: "string" },
                socDesc: { type: "string" },
                addVoltage: { type: "string" },
                addVoltageResult: { type: "string" },
                totalVoltage: { type: "string" },
                totalVoltageResult: { type: "string" },
                addVoltageDesc: { type: "string" },
                maxVoltage: { type: "string" },
                maxVoltageResult: { type: "string" },
                maxVoltageDesc: { type: "string" },
                minVoltage: { type: "string" },
                minVoltageResult: { type: "string" },
                minVoltageDesc: { type: "string" },
                maxTemperature: { type: "string" },
                maxTemperatureResult: { type: "string" },
                maxTemperatureDesc: { type: "string" },
                minTemperature: { type: "string" },
                minTemperatureResult: { type: "string" },
                minTemperatureDesc: { type: "string" },
                diffTemperature: { type: "string" },
                diffTemperatureResult: { type: "string" },
                diffTemperatureDesc: { type: "string" },
                batteryBalance: {
                  type: "string",
                  enum: ["LOW", "MIDDLE", "HIGH"],
                },
                diffVoltage: { type: "string" },
                diffVoltageResult: { type: "string" },
                diffVoltageDesc: { type: "string" },
                chargePositive: { type: "string" },
                chargePositiveResult: { type: "string" },
                chargeNegative: { type: "string" },
                chargeNegativeResult: { type: "string" },
                chargePositiveDesc: { type: "string" },
                nochargePositive: { type: "string" },
                nochargePositiveResult: { type: "string" },
                nochargeNegative: { type: "string" },
                nochargeNegativeResult: { type: "string" },
                nochargePositiveDesc: { type: "string" },
                status: {
                  type: "string",
                  enum: [
                    "CREATING",
                    "WAITING",
                    "MAINTAINING",
                    "REPARING",
                    "PENDING",
                    "PASSED",
                  ],
                },
              },
            },
            repair: { type: "string", description: "关联维修单 id" },
          },
        },
        {
          additionalProperties: false,
          type: "object",
          required: ["id"],
          properties: {
            id: { type: "string" },
            updateAt: { tsType: "Date", type: "string", format: "date-time" },
            updateBy: { type: "string" },
            createAt: { tsType: "Date", type: "string", format: "date-time" },
            createBy: { type: "string" },
          },
        },
      ],
    },
  },
};
export const listMaintainsReqSchema = {
  additionalProperties: false,
  type: "object",
  required: [],
  properties: {
    query: {
      additionalProperties: false,
      type: "object",
      required: [],
      properties: {
        _limit: {
          type: "integer",
          format: "int32",
          default: 10,
          maximum: 1000,
        },
        _offset: { type: "integer", format: "int32", default: 0 },
        _sort: { type: "string" },
        _select: { type: "array", items: { type: "string" } },
        id_like: { type: "string", minLength: 1 },
        status: {
          type: "string",
          enum: [
            "CREATING",
            "WAITING",
            "MAINTAINING",
            "REPARING",
            "MAINTAINED",
            "PENDING",
            "PASSED",
          ],
        },
        createAt_gt: { tsType: "Date", type: "string", format: "date-time" },
        createAt_lt: { tsType: "Date", type: "string", format: "date-time" },
        terminal_like: { type: "string", minLength: 1 },
        plate_like: { type: "string", minLength: 1 },
        crm_like: { type: "string", minLength: 1 },
        vin_like: { type: "string", minLength: 1 },
      },
    },
  },
};
export const listMaintainsResSchema = {
  additionalProperties: false,
  type: "object",
  required: [],
  properties: {
    content: {
      type: "array",
      items: {
        allOf: [
          {
            additionalProperties: false,
            type: "object",
            properties: {
              ticket: { type: "string", description: "关联的工单 id" },
              status: {
                type: "string",
                enum: [
                  "CREATING",
                  "WAITING",
                  "MAINTAINING",
                  "REPARING",
                  "PENDING",
                  "PASSED",
                ],
                description: "维保单工单状态",
              },
              rejected: { type: "boolean", description: "工单曾经被驳回" },
              crm: { type: "string", description: "CRM 订单号" },
              vehicle: { type: "string", description: "关联车辆 id" },
              terminal: { type: "string", description: "关联车辆 终端用户" },
              plate: { type: "string", description: "关联车辆 车牌号" },
              vin: { type: "string", description: "关联车辆 vin" },
              brands: { type: "string", description: "关联车辆 整车品牌" },
              appearance: { type: "string", description: "外观检查组" },
              software: { type: "string", description: "软件诊断组" },
              closeAt: {
                tsType: "Date",
                type: "string",
                format: "date-time",
                description: "完工时间",
              },
              appearanceRecord: {
                additionalProperties: false,
                type: "object",
                description: "维保单外观诊断记录",
                required: [
                  "appearanceSignAddress",
                  "appearanceArrivalAt",
                  "appearanceWorkers",
                  "meterAlarm",
                  "boxDamage",
                  "electricLeakage",
                  "valveLoose",
                  "coverAbnormal",
                  "headLoose",
                  "boltLoose",
                  "msdAbnormal",
                  "hvWireWear",
                  "lvWireWear",
                  "hvConnectorFasten",
                  "lvConnectorFasten",
                  "frontPic",
                  "nameplatePic",
                  "meterPic",
                  "batteryPic",
                ],
                properties: {
                  appearanceSignAddress: { type: "string" },
                  appearanceArrivalAt: {
                    tsType: "Date",
                    type: "string",
                    format: "date-time",
                  },
                  appearanceRouteMap: { type: "string" },
                  appearanceWorkers: {
                    type: "array",
                    items: { type: "string" },
                  },
                  meterAlarm: { type: "boolean" },
                  meterAlarmResult: { type: "boolean" },
                  meterAlarmDesc: { type: "string" },
                  boxDamage: { type: "boolean" },
                  boxDamageResult: { type: "boolean" },
                  boxDamageDesc: { type: "string" },
                  electricLeakage: { type: "boolean" },
                  electricLeakageResult: { type: "boolean" },
                  electricLeakageDesc: { type: "string" },
                  valveLoose: { type: "boolean" },
                  valveLooseResult: { type: "boolean" },
                  valveLooseDesc: { type: "string" },
                  coverAbnormal: { type: "boolean" },
                  coverAbnormalResult: { type: "boolean" },
                  coverAbnormalDesc: { type: "string" },
                  headLoose: { type: "boolean" },
                  headLooseResult: { type: "boolean" },
                  headLooseDesc: { type: "string" },
                  boltLoose: { type: "boolean" },
                  boltLooseResult: { type: "boolean" },
                  boltLooseDesc: { type: "string" },
                  msdAbnormal: { type: "boolean" },
                  msdAbnormalResult: { type: "boolean" },
                  msdAbnormalDesc: { type: "string" },
                  hvWireWear: { type: "boolean" },
                  hvWireWearResult: { type: "boolean" },
                  hvWireWearDesc: { type: "string" },
                  lvWireWear: { type: "boolean" },
                  lvWireWearResult: { type: "boolean" },
                  lvWireWearDesc: { type: "string" },
                  hvConnectorFasten: { type: "boolean" },
                  hvConnectorFastenResult: { type: "boolean" },
                  hvConnectorFastenDesc: { type: "string" },
                  lvConnectorFasten: { type: "boolean" },
                  lvConnectorFastenResult: { type: "boolean" },
                  lvConnectorFastenDesc: { type: "string" },
                  frontPic: { type: "array", items: { type: "string" } },
                  nameplatePic: { type: "array", items: { type: "string" } },
                  meterPic: { type: "array", items: { type: "string" } },
                  batteryPic: { type: "array", items: { type: "string" } },
                  status: {
                    type: "string",
                    enum: [
                      "CREATING",
                      "WAITING",
                      "MAINTAINING",
                      "REPARING",
                      "PENDING",
                      "PASSED",
                    ],
                  },
                },
              },
              softwareRecord: {
                additionalProperties: false,
                type: "object",
                description: "维保单软件诊断记录",
                required: [
                  "softwareSignAddress",
                  "softwareArrivalAt",
                  "softwareWorkers",
                  "softwareStartPic",
                  "softwareEndPic",
                  "soh",
                  "current",
                  "soc",
                  "roc",
                  "addVoltage",
                  "totalVoltage",
                  "maxVoltage",
                  "minVoltage",
                  "maxTemperature",
                  "minTemperature",
                  "diffTemperature",
                  "batteryBalance",
                  "diffVoltage",
                  "chargePositive",
                  "chargeNegative",
                  "nochargePositive",
                  "nochargeNegative",
                ],
                properties: {
                  softwareSignAddress: { type: "string" },
                  softwareArrivalAt: {
                    tsType: "Date",
                    type: "string",
                    format: "date-time",
                  },
                  softwareRouteMap: { type: "string" },
                  softwareWorkers: { type: "array", items: { type: "string" } },
                  softwareStartPic: {
                    type: "array",
                    items: { type: "string" },
                  },
                  softwareEndPic: { type: "array", items: { type: "string" } },
                  soh: { type: "string" },
                  sohResult: { type: "string" },
                  sohDesc: { type: "string" },
                  current: { type: "string" },
                  currentResult: { type: "string" },
                  currentDesc: { type: "string" },
                  soc: { type: "string" },
                  socResult: { type: "string" },
                  roc: { type: "string" },
                  rocResult: { type: "string" },
                  socDesc: { type: "string" },
                  addVoltage: { type: "string" },
                  addVoltageResult: { type: "string" },
                  totalVoltage: { type: "string" },
                  totalVoltageResult: { type: "string" },
                  addVoltageDesc: { type: "string" },
                  maxVoltage: { type: "string" },
                  maxVoltageResult: { type: "string" },
                  maxVoltageDesc: { type: "string" },
                  minVoltage: { type: "string" },
                  minVoltageResult: { type: "string" },
                  minVoltageDesc: { type: "string" },
                  maxTemperature: { type: "string" },
                  maxTemperatureResult: { type: "string" },
                  maxTemperatureDesc: { type: "string" },
                  minTemperature: { type: "string" },
                  minTemperatureResult: { type: "string" },
                  minTemperatureDesc: { type: "string" },
                  diffTemperature: { type: "string" },
                  diffTemperatureResult: { type: "string" },
                  diffTemperatureDesc: { type: "string" },
                  batteryBalance: {
                    type: "string",
                    enum: ["LOW", "MIDDLE", "HIGH"],
                  },
                  diffVoltage: { type: "string" },
                  diffVoltageResult: { type: "string" },
                  diffVoltageDesc: { type: "string" },
                  chargePositive: { type: "string" },
                  chargePositiveResult: { type: "string" },
                  chargeNegative: { type: "string" },
                  chargeNegativeResult: { type: "string" },
                  chargePositiveDesc: { type: "string" },
                  nochargePositive: { type: "string" },
                  nochargePositiveResult: { type: "string" },
                  nochargeNegative: { type: "string" },
                  nochargeNegativeResult: { type: "string" },
                  nochargePositiveDesc: { type: "string" },
                  status: {
                    type: "string",
                    enum: [
                      "CREATING",
                      "WAITING",
                      "MAINTAINING",
                      "REPARING",
                      "PENDING",
                      "PASSED",
                    ],
                  },
                },
              },
              repair: { type: "string", description: "关联维修单 id" },
            },
          },
          {
            additionalProperties: false,
            type: "object",
            required: ["id"],
            properties: {
              id: { type: "string" },
              updateAt: { tsType: "Date", type: "string", format: "date-time" },
              updateBy: { type: "string" },
              createAt: { tsType: "Date", type: "string", format: "date-time" },
              createBy: { type: "string" },
            },
          },
        ],
      },
    },
    headers: {
      additionalProperties: false,
      type: "object",
      required: ["X-Total-Count"],
      properties: { "X-Total-Count": { type: "integer" } },
    },
  },
};
export const getMaintainReqSchema = {
  additionalProperties: false,
  type: "object",
  required: ["maintainId"],
  properties: { maintainId: { type: "string" } },
};
export const getMaintainResSchema = {
  additionalProperties: false,
  type: "object",
  required: [],
  properties: {
    content: {
      allOf: [
        {
          additionalProperties: false,
          type: "object",
          properties: {
            ticket: { type: "string", description: "关联的工单 id" },
            status: {
              type: "string",
              enum: [
                "CREATING",
                "WAITING",
                "MAINTAINING",
                "REPARING",
                "PENDING",
                "PASSED",
              ],
              description: "维保单工单状态",
            },
            rejected: { type: "boolean", description: "工单曾经被驳回" },
            crm: { type: "string", description: "CRM 订单号" },
            vehicle: { type: "string", description: "关联车辆 id" },
            terminal: { type: "string", description: "关联车辆 终端用户" },
            plate: { type: "string", description: "关联车辆 车牌号" },
            vin: { type: "string", description: "关联车辆 vin" },
            brands: { type: "string", description: "关联车辆 整车品牌" },
            appearance: { type: "string", description: "外观检查组" },
            software: { type: "string", description: "软件诊断组" },
            closeAt: {
              tsType: "Date",
              type: "string",
              format: "date-time",
              description: "完工时间",
            },
            appearanceRecord: {
              additionalProperties: false,
              type: "object",
              description: "维保单外观诊断记录",
              required: [
                "appearanceSignAddress",
                "appearanceArrivalAt",
                "appearanceWorkers",
                "meterAlarm",
                "boxDamage",
                "electricLeakage",
                "valveLoose",
                "coverAbnormal",
                "headLoose",
                "boltLoose",
                "msdAbnormal",
                "hvWireWear",
                "lvWireWear",
                "hvConnectorFasten",
                "lvConnectorFasten",
                "frontPic",
                "nameplatePic",
                "meterPic",
                "batteryPic",
              ],
              properties: {
                appearanceSignAddress: { type: "string" },
                appearanceArrivalAt: {
                  tsType: "Date",
                  type: "string",
                  format: "date-time",
                },
                appearanceRouteMap: { type: "string" },
                appearanceWorkers: { type: "array", items: { type: "string" } },
                meterAlarm: { type: "boolean" },
                meterAlarmResult: { type: "boolean" },
                meterAlarmDesc: { type: "string" },
                boxDamage: { type: "boolean" },
                boxDamageResult: { type: "boolean" },
                boxDamageDesc: { type: "string" },
                electricLeakage: { type: "boolean" },
                electricLeakageResult: { type: "boolean" },
                electricLeakageDesc: { type: "string" },
                valveLoose: { type: "boolean" },
                valveLooseResult: { type: "boolean" },
                valveLooseDesc: { type: "string" },
                coverAbnormal: { type: "boolean" },
                coverAbnormalResult: { type: "boolean" },
                coverAbnormalDesc: { type: "string" },
                headLoose: { type: "boolean" },
                headLooseResult: { type: "boolean" },
                headLooseDesc: { type: "string" },
                boltLoose: { type: "boolean" },
                boltLooseResult: { type: "boolean" },
                boltLooseDesc: { type: "string" },
                msdAbnormal: { type: "boolean" },
                msdAbnormalResult: { type: "boolean" },
                msdAbnormalDesc: { type: "string" },
                hvWireWear: { type: "boolean" },
                hvWireWearResult: { type: "boolean" },
                hvWireWearDesc: { type: "string" },
                lvWireWear: { type: "boolean" },
                lvWireWearResult: { type: "boolean" },
                lvWireWearDesc: { type: "string" },
                hvConnectorFasten: { type: "boolean" },
                hvConnectorFastenResult: { type: "boolean" },
                hvConnectorFastenDesc: { type: "string" },
                lvConnectorFasten: { type: "boolean" },
                lvConnectorFastenResult: { type: "boolean" },
                lvConnectorFastenDesc: { type: "string" },
                frontPic: { type: "array", items: { type: "string" } },
                nameplatePic: { type: "array", items: { type: "string" } },
                meterPic: { type: "array", items: { type: "string" } },
                batteryPic: { type: "array", items: { type: "string" } },
                status: {
                  type: "string",
                  enum: [
                    "CREATING",
                    "WAITING",
                    "MAINTAINING",
                    "REPARING",
                    "PENDING",
                    "PASSED",
                  ],
                },
              },
            },
            softwareRecord: {
              additionalProperties: false,
              type: "object",
              description: "维保单软件诊断记录",
              required: [
                "softwareSignAddress",
                "softwareArrivalAt",
                "softwareWorkers",
                "softwareStartPic",
                "softwareEndPic",
                "soh",
                "current",
                "soc",
                "roc",
                "addVoltage",
                "totalVoltage",
                "maxVoltage",
                "minVoltage",
                "maxTemperature",
                "minTemperature",
                "diffTemperature",
                "batteryBalance",
                "diffVoltage",
                "chargePositive",
                "chargeNegative",
                "nochargePositive",
                "nochargeNegative",
              ],
              properties: {
                softwareSignAddress: { type: "string" },
                softwareArrivalAt: {
                  tsType: "Date",
                  type: "string",
                  format: "date-time",
                },
                softwareRouteMap: { type: "string" },
                softwareWorkers: { type: "array", items: { type: "string" } },
                softwareStartPic: { type: "array", items: { type: "string" } },
                softwareEndPic: { type: "array", items: { type: "string" } },
                soh: { type: "string" },
                sohResult: { type: "string" },
                sohDesc: { type: "string" },
                current: { type: "string" },
                currentResult: { type: "string" },
                currentDesc: { type: "string" },
                soc: { type: "string" },
                socResult: { type: "string" },
                roc: { type: "string" },
                rocResult: { type: "string" },
                socDesc: { type: "string" },
                addVoltage: { type: "string" },
                addVoltageResult: { type: "string" },
                totalVoltage: { type: "string" },
                totalVoltageResult: { type: "string" },
                addVoltageDesc: { type: "string" },
                maxVoltage: { type: "string" },
                maxVoltageResult: { type: "string" },
                maxVoltageDesc: { type: "string" },
                minVoltage: { type: "string" },
                minVoltageResult: { type: "string" },
                minVoltageDesc: { type: "string" },
                maxTemperature: { type: "string" },
                maxTemperatureResult: { type: "string" },
                maxTemperatureDesc: { type: "string" },
                minTemperature: { type: "string" },
                minTemperatureResult: { type: "string" },
                minTemperatureDesc: { type: "string" },
                diffTemperature: { type: "string" },
                diffTemperatureResult: { type: "string" },
                diffTemperatureDesc: { type: "string" },
                batteryBalance: {
                  type: "string",
                  enum: ["LOW", "MIDDLE", "HIGH"],
                },
                diffVoltage: { type: "string" },
                diffVoltageResult: { type: "string" },
                diffVoltageDesc: { type: "string" },
                chargePositive: { type: "string" },
                chargePositiveResult: { type: "string" },
                chargeNegative: { type: "string" },
                chargeNegativeResult: { type: "string" },
                chargePositiveDesc: { type: "string" },
                nochargePositive: { type: "string" },
                nochargePositiveResult: { type: "string" },
                nochargeNegative: { type: "string" },
                nochargeNegativeResult: { type: "string" },
                nochargePositiveDesc: { type: "string" },
                status: {
                  type: "string",
                  enum: [
                    "CREATING",
                    "WAITING",
                    "MAINTAINING",
                    "REPARING",
                    "PENDING",
                    "PASSED",
                  ],
                },
              },
            },
            repair: { type: "string", description: "关联维修单 id" },
          },
        },
        {
          additionalProperties: false,
          type: "object",
          required: ["id"],
          properties: {
            id: { type: "string" },
            updateAt: { tsType: "Date", type: "string", format: "date-time" },
            updateBy: { type: "string" },
            createAt: { tsType: "Date", type: "string", format: "date-time" },
            createBy: { type: "string" },
          },
        },
      ],
    },
  },
};
export const updateMaintainReqSchema = {
  additionalProperties: false,
  type: "object",
  required: ["maintainId", "body"],
  properties: {
    maintainId: { type: "string" },
    body: {
      additionalProperties: false,
      type: "object",
      properties: {
        ticket: { type: "string", description: "关联的工单 id" },
        status: {
          type: "string",
          enum: [
            "CREATING",
            "WAITING",
            "MAINTAINING",
            "REPARING",
            "PENDING",
            "PASSED",
          ],
          description: "维保单工单状态",
        },
        rejected: { type: "boolean", description: "工单曾经被驳回" },
        crm: { type: "string", description: "CRM 订单号" },
        vehicle: { type: "string", description: "关联车辆 id" },
        terminal: { type: "string", description: "关联车辆 终端用户" },
        plate: { type: "string", description: "关联车辆 车牌号" },
        vin: { type: "string", description: "关联车辆 vin" },
        brands: { type: "string", description: "关联车辆 整车品牌" },
        appearance: { type: "string", description: "外观检查组" },
        software: { type: "string", description: "软件诊断组" },
        closeAt: {
          tsType: "Date",
          type: "string",
          format: "date-time",
          description: "完工时间",
        },
        appearanceRecord: {
          additionalProperties: false,
          type: "object",
          description: "维保单外观诊断记录",
          required: [
            "appearanceSignAddress",
            "appearanceArrivalAt",
            "appearanceWorkers",
            "meterAlarm",
            "boxDamage",
            "electricLeakage",
            "valveLoose",
            "coverAbnormal",
            "headLoose",
            "boltLoose",
            "msdAbnormal",
            "hvWireWear",
            "lvWireWear",
            "hvConnectorFasten",
            "lvConnectorFasten",
            "frontPic",
            "nameplatePic",
            "meterPic",
            "batteryPic",
          ],
          properties: {
            appearanceSignAddress: { type: "string" },
            appearanceArrivalAt: {
              tsType: "Date",
              type: "string",
              format: "date-time",
            },
            appearanceRouteMap: { type: "string" },
            appearanceWorkers: { type: "array", items: { type: "string" } },
            meterAlarm: { type: "boolean" },
            meterAlarmResult: { type: "boolean" },
            meterAlarmDesc: { type: "string" },
            boxDamage: { type: "boolean" },
            boxDamageResult: { type: "boolean" },
            boxDamageDesc: { type: "string" },
            electricLeakage: { type: "boolean" },
            electricLeakageResult: { type: "boolean" },
            electricLeakageDesc: { type: "string" },
            valveLoose: { type: "boolean" },
            valveLooseResult: { type: "boolean" },
            valveLooseDesc: { type: "string" },
            coverAbnormal: { type: "boolean" },
            coverAbnormalResult: { type: "boolean" },
            coverAbnormalDesc: { type: "string" },
            headLoose: { type: "boolean" },
            headLooseResult: { type: "boolean" },
            headLooseDesc: { type: "string" },
            boltLoose: { type: "boolean" },
            boltLooseResult: { type: "boolean" },
            boltLooseDesc: { type: "string" },
            msdAbnormal: { type: "boolean" },
            msdAbnormalResult: { type: "boolean" },
            msdAbnormalDesc: { type: "string" },
            hvWireWear: { type: "boolean" },
            hvWireWearResult: { type: "boolean" },
            hvWireWearDesc: { type: "string" },
            lvWireWear: { type: "boolean" },
            lvWireWearResult: { type: "boolean" },
            lvWireWearDesc: { type: "string" },
            hvConnectorFasten: { type: "boolean" },
            hvConnectorFastenResult: { type: "boolean" },
            hvConnectorFastenDesc: { type: "string" },
            lvConnectorFasten: { type: "boolean" },
            lvConnectorFastenResult: { type: "boolean" },
            lvConnectorFastenDesc: { type: "string" },
            frontPic: { type: "array", items: { type: "string" } },
            nameplatePic: { type: "array", items: { type: "string" } },
            meterPic: { type: "array", items: { type: "string" } },
            batteryPic: { type: "array", items: { type: "string" } },
            status: {
              type: "string",
              enum: [
                "CREATING",
                "WAITING",
                "MAINTAINING",
                "REPARING",
                "PENDING",
                "PASSED",
              ],
            },
          },
        },
        softwareRecord: {
          additionalProperties: false,
          type: "object",
          description: "维保单软件诊断记录",
          required: [
            "softwareSignAddress",
            "softwareArrivalAt",
            "softwareWorkers",
            "softwareStartPic",
            "softwareEndPic",
            "soh",
            "current",
            "soc",
            "roc",
            "addVoltage",
            "totalVoltage",
            "maxVoltage",
            "minVoltage",
            "maxTemperature",
            "minTemperature",
            "diffTemperature",
            "batteryBalance",
            "diffVoltage",
            "chargePositive",
            "chargeNegative",
            "nochargePositive",
            "nochargeNegative",
          ],
          properties: {
            softwareSignAddress: { type: "string" },
            softwareArrivalAt: {
              tsType: "Date",
              type: "string",
              format: "date-time",
            },
            softwareRouteMap: { type: "string" },
            softwareWorkers: { type: "array", items: { type: "string" } },
            softwareStartPic: { type: "array", items: { type: "string" } },
            softwareEndPic: { type: "array", items: { type: "string" } },
            soh: { type: "string" },
            sohResult: { type: "string" },
            sohDesc: { type: "string" },
            current: { type: "string" },
            currentResult: { type: "string" },
            currentDesc: { type: "string" },
            soc: { type: "string" },
            socResult: { type: "string" },
            roc: { type: "string" },
            rocResult: { type: "string" },
            socDesc: { type: "string" },
            addVoltage: { type: "string" },
            addVoltageResult: { type: "string" },
            totalVoltage: { type: "string" },
            totalVoltageResult: { type: "string" },
            addVoltageDesc: { type: "string" },
            maxVoltage: { type: "string" },
            maxVoltageResult: { type: "string" },
            maxVoltageDesc: { type: "string" },
            minVoltage: { type: "string" },
            minVoltageResult: { type: "string" },
            minVoltageDesc: { type: "string" },
            maxTemperature: { type: "string" },
            maxTemperatureResult: { type: "string" },
            maxTemperatureDesc: { type: "string" },
            minTemperature: { type: "string" },
            minTemperatureResult: { type: "string" },
            minTemperatureDesc: { type: "string" },
            diffTemperature: { type: "string" },
            diffTemperatureResult: { type: "string" },
            diffTemperatureDesc: { type: "string" },
            batteryBalance: { type: "string", enum: ["LOW", "MIDDLE", "HIGH"] },
            diffVoltage: { type: "string" },
            diffVoltageResult: { type: "string" },
            diffVoltageDesc: { type: "string" },
            chargePositive: { type: "string" },
            chargePositiveResult: { type: "string" },
            chargeNegative: { type: "string" },
            chargeNegativeResult: { type: "string" },
            chargePositiveDesc: { type: "string" },
            nochargePositive: { type: "string" },
            nochargePositiveResult: { type: "string" },
            nochargeNegative: { type: "string" },
            nochargeNegativeResult: { type: "string" },
            nochargePositiveDesc: { type: "string" },
            status: {
              type: "string",
              enum: [
                "CREATING",
                "WAITING",
                "MAINTAINING",
                "REPARING",
                "PENDING",
                "PASSED",
              ],
            },
          },
        },
        repair: { type: "string", description: "关联维修单 id" },
      },
    },
  },
};
export const updateMaintainResSchema = {
  additionalProperties: false,
  type: "object",
  required: [],
  properties: {
    content: {
      allOf: [
        {
          additionalProperties: false,
          type: "object",
          properties: {
            ticket: { type: "string", description: "关联的工单 id" },
            status: {
              type: "string",
              enum: [
                "CREATING",
                "WAITING",
                "MAINTAINING",
                "REPARING",
                "PENDING",
                "PASSED",
              ],
              description: "维保单工单状态",
            },
            rejected: { type: "boolean", description: "工单曾经被驳回" },
            crm: { type: "string", description: "CRM 订单号" },
            vehicle: { type: "string", description: "关联车辆 id" },
            terminal: { type: "string", description: "关联车辆 终端用户" },
            plate: { type: "string", description: "关联车辆 车牌号" },
            vin: { type: "string", description: "关联车辆 vin" },
            brands: { type: "string", description: "关联车辆 整车品牌" },
            appearance: { type: "string", description: "外观检查组" },
            software: { type: "string", description: "软件诊断组" },
            closeAt: {
              tsType: "Date",
              type: "string",
              format: "date-time",
              description: "完工时间",
            },
            appearanceRecord: {
              additionalProperties: false,
              type: "object",
              description: "维保单外观诊断记录",
              required: [
                "appearanceSignAddress",
                "appearanceArrivalAt",
                "appearanceWorkers",
                "meterAlarm",
                "boxDamage",
                "electricLeakage",
                "valveLoose",
                "coverAbnormal",
                "headLoose",
                "boltLoose",
                "msdAbnormal",
                "hvWireWear",
                "lvWireWear",
                "hvConnectorFasten",
                "lvConnectorFasten",
                "frontPic",
                "nameplatePic",
                "meterPic",
                "batteryPic",
              ],
              properties: {
                appearanceSignAddress: { type: "string" },
                appearanceArrivalAt: {
                  tsType: "Date",
                  type: "string",
                  format: "date-time",
                },
                appearanceRouteMap: { type: "string" },
                appearanceWorkers: { type: "array", items: { type: "string" } },
                meterAlarm: { type: "boolean" },
                meterAlarmResult: { type: "boolean" },
                meterAlarmDesc: { type: "string" },
                boxDamage: { type: "boolean" },
                boxDamageResult: { type: "boolean" },
                boxDamageDesc: { type: "string" },
                electricLeakage: { type: "boolean" },
                electricLeakageResult: { type: "boolean" },
                electricLeakageDesc: { type: "string" },
                valveLoose: { type: "boolean" },
                valveLooseResult: { type: "boolean" },
                valveLooseDesc: { type: "string" },
                coverAbnormal: { type: "boolean" },
                coverAbnormalResult: { type: "boolean" },
                coverAbnormalDesc: { type: "string" },
                headLoose: { type: "boolean" },
                headLooseResult: { type: "boolean" },
                headLooseDesc: { type: "string" },
                boltLoose: { type: "boolean" },
                boltLooseResult: { type: "boolean" },
                boltLooseDesc: { type: "string" },
                msdAbnormal: { type: "boolean" },
                msdAbnormalResult: { type: "boolean" },
                msdAbnormalDesc: { type: "string" },
                hvWireWear: { type: "boolean" },
                hvWireWearResult: { type: "boolean" },
                hvWireWearDesc: { type: "string" },
                lvWireWear: { type: "boolean" },
                lvWireWearResult: { type: "boolean" },
                lvWireWearDesc: { type: "string" },
                hvConnectorFasten: { type: "boolean" },
                hvConnectorFastenResult: { type: "boolean" },
                hvConnectorFastenDesc: { type: "string" },
                lvConnectorFasten: { type: "boolean" },
                lvConnectorFastenResult: { type: "boolean" },
                lvConnectorFastenDesc: { type: "string" },
                frontPic: { type: "array", items: { type: "string" } },
                nameplatePic: { type: "array", items: { type: "string" } },
                meterPic: { type: "array", items: { type: "string" } },
                batteryPic: { type: "array", items: { type: "string" } },
                status: {
                  type: "string",
                  enum: [
                    "CREATING",
                    "WAITING",
                    "MAINTAINING",
                    "REPARING",
                    "PENDING",
                    "PASSED",
                  ],
                },
              },
            },
            softwareRecord: {
              additionalProperties: false,
              type: "object",
              description: "维保单软件诊断记录",
              required: [
                "softwareSignAddress",
                "softwareArrivalAt",
                "softwareWorkers",
                "softwareStartPic",
                "softwareEndPic",
                "soh",
                "current",
                "soc",
                "roc",
                "addVoltage",
                "totalVoltage",
                "maxVoltage",
                "minVoltage",
                "maxTemperature",
                "minTemperature",
                "diffTemperature",
                "batteryBalance",
                "diffVoltage",
                "chargePositive",
                "chargeNegative",
                "nochargePositive",
                "nochargeNegative",
              ],
              properties: {
                softwareSignAddress: { type: "string" },
                softwareArrivalAt: {
                  tsType: "Date",
                  type: "string",
                  format: "date-time",
                },
                softwareRouteMap: { type: "string" },
                softwareWorkers: { type: "array", items: { type: "string" } },
                softwareStartPic: { type: "array", items: { type: "string" } },
                softwareEndPic: { type: "array", items: { type: "string" } },
                soh: { type: "string" },
                sohResult: { type: "string" },
                sohDesc: { type: "string" },
                current: { type: "string" },
                currentResult: { type: "string" },
                currentDesc: { type: "string" },
                soc: { type: "string" },
                socResult: { type: "string" },
                roc: { type: "string" },
                rocResult: { type: "string" },
                socDesc: { type: "string" },
                addVoltage: { type: "string" },
                addVoltageResult: { type: "string" },
                totalVoltage: { type: "string" },
                totalVoltageResult: { type: "string" },
                addVoltageDesc: { type: "string" },
                maxVoltage: { type: "string" },
                maxVoltageResult: { type: "string" },
                maxVoltageDesc: { type: "string" },
                minVoltage: { type: "string" },
                minVoltageResult: { type: "string" },
                minVoltageDesc: { type: "string" },
                maxTemperature: { type: "string" },
                maxTemperatureResult: { type: "string" },
                maxTemperatureDesc: { type: "string" },
                minTemperature: { type: "string" },
                minTemperatureResult: { type: "string" },
                minTemperatureDesc: { type: "string" },
                diffTemperature: { type: "string" },
                diffTemperatureResult: { type: "string" },
                diffTemperatureDesc: { type: "string" },
                batteryBalance: {
                  type: "string",
                  enum: ["LOW", "MIDDLE", "HIGH"],
                },
                diffVoltage: { type: "string" },
                diffVoltageResult: { type: "string" },
                diffVoltageDesc: { type: "string" },
                chargePositive: { type: "string" },
                chargePositiveResult: { type: "string" },
                chargeNegative: { type: "string" },
                chargeNegativeResult: { type: "string" },
                chargePositiveDesc: { type: "string" },
                nochargePositive: { type: "string" },
                nochargePositiveResult: { type: "string" },
                nochargeNegative: { type: "string" },
                nochargeNegativeResult: { type: "string" },
                nochargePositiveDesc: { type: "string" },
                status: {
                  type: "string",
                  enum: [
                    "CREATING",
                    "WAITING",
                    "MAINTAINING",
                    "REPARING",
                    "PENDING",
                    "PASSED",
                  ],
                },
              },
            },
            repair: { type: "string", description: "关联维修单 id" },
          },
        },
        {
          additionalProperties: false,
          type: "object",
          required: ["id"],
          properties: {
            id: { type: "string" },
            updateAt: { tsType: "Date", type: "string", format: "date-time" },
            updateBy: { type: "string" },
            createAt: { tsType: "Date", type: "string", format: "date-time" },
            createBy: { type: "string" },
          },
        },
      ],
    },
  },
};
export const deleteMaintainReqSchema = {
  additionalProperties: false,
  type: "object",
  required: ["maintainId"],
  properties: { maintainId: { type: "string" } },
};
export const updateAppearanceRecordReqSchema = {
  additionalProperties: false,
  type: "object",
  required: ["maintainId", "body"],
  properties: {
    maintainId: { type: "string" },
    body: {
      additionalProperties: false,
      type: "object",
      description: "维保单外观诊断记录",
      required: [
        "appearanceSignAddress",
        "appearanceArrivalAt",
        "appearanceWorkers",
        "meterAlarm",
        "boxDamage",
        "electricLeakage",
        "valveLoose",
        "coverAbnormal",
        "headLoose",
        "boltLoose",
        "msdAbnormal",
        "hvWireWear",
        "lvWireWear",
        "hvConnectorFasten",
        "lvConnectorFasten",
        "frontPic",
        "nameplatePic",
        "meterPic",
        "batteryPic",
      ],
      properties: {
        appearanceSignAddress: { type: "string" },
        appearanceArrivalAt: {
          tsType: "Date",
          type: "string",
          format: "date-time",
        },
        appearanceRouteMap: { type: "string" },
        appearanceWorkers: { type: "array", items: { type: "string" } },
        meterAlarm: { type: "boolean" },
        meterAlarmResult: { type: "boolean" },
        meterAlarmDesc: { type: "string" },
        boxDamage: { type: "boolean" },
        boxDamageResult: { type: "boolean" },
        boxDamageDesc: { type: "string" },
        electricLeakage: { type: "boolean" },
        electricLeakageResult: { type: "boolean" },
        electricLeakageDesc: { type: "string" },
        valveLoose: { type: "boolean" },
        valveLooseResult: { type: "boolean" },
        valveLooseDesc: { type: "string" },
        coverAbnormal: { type: "boolean" },
        coverAbnormalResult: { type: "boolean" },
        coverAbnormalDesc: { type: "string" },
        headLoose: { type: "boolean" },
        headLooseResult: { type: "boolean" },
        headLooseDesc: { type: "string" },
        boltLoose: { type: "boolean" },
        boltLooseResult: { type: "boolean" },
        boltLooseDesc: { type: "string" },
        msdAbnormal: { type: "boolean" },
        msdAbnormalResult: { type: "boolean" },
        msdAbnormalDesc: { type: "string" },
        hvWireWear: { type: "boolean" },
        hvWireWearResult: { type: "boolean" },
        hvWireWearDesc: { type: "string" },
        lvWireWear: { type: "boolean" },
        lvWireWearResult: { type: "boolean" },
        lvWireWearDesc: { type: "string" },
        hvConnectorFasten: { type: "boolean" },
        hvConnectorFastenResult: { type: "boolean" },
        hvConnectorFastenDesc: { type: "string" },
        lvConnectorFasten: { type: "boolean" },
        lvConnectorFastenResult: { type: "boolean" },
        lvConnectorFastenDesc: { type: "string" },
        frontPic: { type: "array", items: { type: "string" } },
        nameplatePic: { type: "array", items: { type: "string" } },
        meterPic: { type: "array", items: { type: "string" } },
        batteryPic: { type: "array", items: { type: "string" } },
        status: {
          type: "string",
          enum: [
            "CREATING",
            "WAITING",
            "MAINTAINING",
            "REPARING",
            "PENDING",
            "PASSED",
          ],
        },
      },
    },
  },
};
export const updateAppearanceRecordResSchema = {
  additionalProperties: false,
  type: "object",
  required: [],
  properties: {
    content: {
      additionalProperties: false,
      type: "object",
      description: "维保单外观诊断记录",
      required: [
        "appearanceSignAddress",
        "appearanceArrivalAt",
        "appearanceWorkers",
        "meterAlarm",
        "boxDamage",
        "electricLeakage",
        "valveLoose",
        "coverAbnormal",
        "headLoose",
        "boltLoose",
        "msdAbnormal",
        "hvWireWear",
        "lvWireWear",
        "hvConnectorFasten",
        "lvConnectorFasten",
        "frontPic",
        "nameplatePic",
        "meterPic",
        "batteryPic",
      ],
      properties: {
        appearanceSignAddress: { type: "string" },
        appearanceArrivalAt: {
          tsType: "Date",
          type: "string",
          format: "date-time",
        },
        appearanceRouteMap: { type: "string" },
        appearanceWorkers: { type: "array", items: { type: "string" } },
        meterAlarm: { type: "boolean" },
        meterAlarmResult: { type: "boolean" },
        meterAlarmDesc: { type: "string" },
        boxDamage: { type: "boolean" },
        boxDamageResult: { type: "boolean" },
        boxDamageDesc: { type: "string" },
        electricLeakage: { type: "boolean" },
        electricLeakageResult: { type: "boolean" },
        electricLeakageDesc: { type: "string" },
        valveLoose: { type: "boolean" },
        valveLooseResult: { type: "boolean" },
        valveLooseDesc: { type: "string" },
        coverAbnormal: { type: "boolean" },
        coverAbnormalResult: { type: "boolean" },
        coverAbnormalDesc: { type: "string" },
        headLoose: { type: "boolean" },
        headLooseResult: { type: "boolean" },
        headLooseDesc: { type: "string" },
        boltLoose: { type: "boolean" },
        boltLooseResult: { type: "boolean" },
        boltLooseDesc: { type: "string" },
        msdAbnormal: { type: "boolean" },
        msdAbnormalResult: { type: "boolean" },
        msdAbnormalDesc: { type: "string" },
        hvWireWear: { type: "boolean" },
        hvWireWearResult: { type: "boolean" },
        hvWireWearDesc: { type: "string" },
        lvWireWear: { type: "boolean" },
        lvWireWearResult: { type: "boolean" },
        lvWireWearDesc: { type: "string" },
        hvConnectorFasten: { type: "boolean" },
        hvConnectorFastenResult: { type: "boolean" },
        hvConnectorFastenDesc: { type: "string" },
        lvConnectorFasten: { type: "boolean" },
        lvConnectorFastenResult: { type: "boolean" },
        lvConnectorFastenDesc: { type: "string" },
        frontPic: { type: "array", items: { type: "string" } },
        nameplatePic: { type: "array", items: { type: "string" } },
        meterPic: { type: "array", items: { type: "string" } },
        batteryPic: { type: "array", items: { type: "string" } },
        status: {
          type: "string",
          enum: [
            "CREATING",
            "WAITING",
            "MAINTAINING",
            "REPARING",
            "PENDING",
            "PASSED",
          ],
        },
      },
    },
  },
};
export const updateSoftwareRecordReqSchema = {
  additionalProperties: false,
  type: "object",
  required: ["maintainId", "body"],
  properties: {
    maintainId: { type: "string" },
    body: {
      additionalProperties: false,
      type: "object",
      description: "维保单软件诊断记录",
      required: [
        "softwareSignAddress",
        "softwareArrivalAt",
        "softwareWorkers",
        "softwareStartPic",
        "softwareEndPic",
        "soh",
        "current",
        "soc",
        "roc",
        "addVoltage",
        "totalVoltage",
        "maxVoltage",
        "minVoltage",
        "maxTemperature",
        "minTemperature",
        "diffTemperature",
        "batteryBalance",
        "diffVoltage",
        "chargePositive",
        "chargeNegative",
        "nochargePositive",
        "nochargeNegative",
      ],
      properties: {
        softwareSignAddress: { type: "string" },
        softwareArrivalAt: {
          tsType: "Date",
          type: "string",
          format: "date-time",
        },
        softwareRouteMap: { type: "string" },
        softwareWorkers: { type: "array", items: { type: "string" } },
        softwareStartPic: { type: "array", items: { type: "string" } },
        softwareEndPic: { type: "array", items: { type: "string" } },
        soh: { type: "string" },
        sohResult: { type: "string" },
        sohDesc: { type: "string" },
        current: { type: "string" },
        currentResult: { type: "string" },
        currentDesc: { type: "string" },
        soc: { type: "string" },
        socResult: { type: "string" },
        roc: { type: "string" },
        rocResult: { type: "string" },
        socDesc: { type: "string" },
        addVoltage: { type: "string" },
        addVoltageResult: { type: "string" },
        totalVoltage: { type: "string" },
        totalVoltageResult: { type: "string" },
        addVoltageDesc: { type: "string" },
        maxVoltage: { type: "string" },
        maxVoltageResult: { type: "string" },
        maxVoltageDesc: { type: "string" },
        minVoltage: { type: "string" },
        minVoltageResult: { type: "string" },
        minVoltageDesc: { type: "string" },
        maxTemperature: { type: "string" },
        maxTemperatureResult: { type: "string" },
        maxTemperatureDesc: { type: "string" },
        minTemperature: { type: "string" },
        minTemperatureResult: { type: "string" },
        minTemperatureDesc: { type: "string" },
        diffTemperature: { type: "string" },
        diffTemperatureResult: { type: "string" },
        diffTemperatureDesc: { type: "string" },
        batteryBalance: { type: "string", enum: ["LOW", "MIDDLE", "HIGH"] },
        diffVoltage: { type: "string" },
        diffVoltageResult: { type: "string" },
        diffVoltageDesc: { type: "string" },
        chargePositive: { type: "string" },
        chargePositiveResult: { type: "string" },
        chargeNegative: { type: "string" },
        chargeNegativeResult: { type: "string" },
        chargePositiveDesc: { type: "string" },
        nochargePositive: { type: "string" },
        nochargePositiveResult: { type: "string" },
        nochargeNegative: { type: "string" },
        nochargeNegativeResult: { type: "string" },
        nochargePositiveDesc: { type: "string" },
        status: {
          type: "string",
          enum: [
            "CREATING",
            "WAITING",
            "MAINTAINING",
            "REPARING",
            "PENDING",
            "PASSED",
          ],
        },
      },
    },
  },
};
export const updateSoftwareRecordResSchema = {
  additionalProperties: false,
  type: "object",
  required: [],
  properties: {
    content: {
      additionalProperties: false,
      type: "object",
      description: "维保单软件诊断记录",
      required: [
        "softwareSignAddress",
        "softwareArrivalAt",
        "softwareWorkers",
        "softwareStartPic",
        "softwareEndPic",
        "soh",
        "current",
        "soc",
        "roc",
        "addVoltage",
        "totalVoltage",
        "maxVoltage",
        "minVoltage",
        "maxTemperature",
        "minTemperature",
        "diffTemperature",
        "batteryBalance",
        "diffVoltage",
        "chargePositive",
        "chargeNegative",
        "nochargePositive",
        "nochargeNegative",
      ],
      properties: {
        softwareSignAddress: { type: "string" },
        softwareArrivalAt: {
          tsType: "Date",
          type: "string",
          format: "date-time",
        },
        softwareRouteMap: { type: "string" },
        softwareWorkers: { type: "array", items: { type: "string" } },
        softwareStartPic: { type: "array", items: { type: "string" } },
        softwareEndPic: { type: "array", items: { type: "string" } },
        soh: { type: "string" },
        sohResult: { type: "string" },
        sohDesc: { type: "string" },
        current: { type: "string" },
        currentResult: { type: "string" },
        currentDesc: { type: "string" },
        soc: { type: "string" },
        socResult: { type: "string" },
        roc: { type: "string" },
        rocResult: { type: "string" },
        socDesc: { type: "string" },
        addVoltage: { type: "string" },
        addVoltageResult: { type: "string" },
        totalVoltage: { type: "string" },
        totalVoltageResult: { type: "string" },
        addVoltageDesc: { type: "string" },
        maxVoltage: { type: "string" },
        maxVoltageResult: { type: "string" },
        maxVoltageDesc: { type: "string" },
        minVoltage: { type: "string" },
        minVoltageResult: { type: "string" },
        minVoltageDesc: { type: "string" },
        maxTemperature: { type: "string" },
        maxTemperatureResult: { type: "string" },
        maxTemperatureDesc: { type: "string" },
        minTemperature: { type: "string" },
        minTemperatureResult: { type: "string" },
        minTemperatureDesc: { type: "string" },
        diffTemperature: { type: "string" },
        diffTemperatureResult: { type: "string" },
        diffTemperatureDesc: { type: "string" },
        batteryBalance: { type: "string", enum: ["LOW", "MIDDLE", "HIGH"] },
        diffVoltage: { type: "string" },
        diffVoltageResult: { type: "string" },
        diffVoltageDesc: { type: "string" },
        chargePositive: { type: "string" },
        chargePositiveResult: { type: "string" },
        chargeNegative: { type: "string" },
        chargeNegativeResult: { type: "string" },
        chargePositiveDesc: { type: "string" },
        nochargePositive: { type: "string" },
        nochargePositiveResult: { type: "string" },
        nochargeNegative: { type: "string" },
        nochargeNegativeResult: { type: "string" },
        nochargePositiveDesc: { type: "string" },
        status: {
          type: "string",
          enum: [
            "CREATING",
            "WAITING",
            "MAINTAINING",
            "REPARING",
            "PENDING",
            "PASSED",
          ],
        },
      },
    },
  },
};
