export const createVehicleReqSchema = {
  additionalProperties: false,
  type: "object",
  required: ["body"],
  properties: {
    body: {
      additionalProperties: false,
      type: "object",
      required: [
        "terminal",
        "purchaseAt",
        "plateAt",
        "operateAt",
        "year",
        "brands",
        "plate",
        "vin",
        "jobNum",
        "catl",
        "batteryPN",
        "batteryNum",
        "power",
        "bmuHardware",
        "bmuSoftware",
        "cscHardware",
        "cscSoftware",
        "rdb",
        "softwarePic",
        "frontPic",
        "nameplatePic",
        "meterPic",
        "batteryPic",
        "createBy",
      ],
      properties: {
        terminal: { type: "string" },
        park: { type: "string" },
        purchaseAt: { tsType: "Date", type: "string", format: "date-time" },
        plateAt: { tsType: "Date", type: "string", format: "date-time" },
        operateAt: { tsType: "Date", type: "string", format: "date-time" },
        retireAt: { tsType: "Date", type: "string", format: "date-time" },
        year: { type: "number" },
        license: {
          type: "array",
          items: {
            additionalProperties: false,
            type: "object",
            properties: {
              name: { type: "string", description: "原始文件名" },
              ossName: { type: "string", description: "oss上的文件名" },
              remark: { type: "string", description: "备注" },
              size: { type: "number", description: "文件大小" },
              status: { type: "string", description: "上传状态" },
              uid: { type: "string", description: "uid" },
              url: { type: "string", description: "url" },
            },
          },
        },
        brands: { type: "string" },
        plate: { type: "string" },
        vin: { type: "string" },
        jobNum: { type: "string" },
        num: { type: "string" },
        catl: { type: "string" },
        batteryPN: { type: "string" },
        batteryNum: { type: "string" },
        batteryPropRight: { type: "string" },
        power: { type: "number" },
        bmuHardware: { type: "string" },
        bmuSoftware: { type: "string" },
        cscHardware: { type: "string" },
        cscSoftware: { type: "string" },
        rdb: { type: "string" },
        remark: { type: "string" },
        status: { type: "string" },
        softwarePic: {
          type: "array",
          items: {
            additionalProperties: false,
            type: "object",
            properties: {
              name: { type: "string", description: "原始文件名" },
              ossName: { type: "string", description: "oss上的文件名" },
              remark: { type: "string", description: "备注" },
              size: { type: "number", description: "文件大小" },
              status: { type: "string", description: "上传状态" },
              uid: { type: "string", description: "uid" },
              url: { type: "string", description: "url" },
            },
          },
        },
        frontPic: {
          type: "array",
          items: {
            additionalProperties: false,
            type: "object",
            properties: {
              name: { type: "string", description: "原始文件名" },
              ossName: { type: "string", description: "oss上的文件名" },
              remark: { type: "string", description: "备注" },
              size: { type: "number", description: "文件大小" },
              status: { type: "string", description: "上传状态" },
              uid: { type: "string", description: "uid" },
              url: { type: "string", description: "url" },
            },
          },
        },
        nameplatePic: {
          type: "array",
          items: {
            additionalProperties: false,
            type: "object",
            properties: {
              name: { type: "string", description: "原始文件名" },
              ossName: { type: "string", description: "oss上的文件名" },
              remark: { type: "string", description: "备注" },
              size: { type: "number", description: "文件大小" },
              status: { type: "string", description: "上传状态" },
              uid: { type: "string", description: "uid" },
              url: { type: "string", description: "url" },
            },
          },
        },
        meterPic: {
          type: "array",
          items: {
            additionalProperties: false,
            type: "object",
            properties: {
              name: { type: "string", description: "原始文件名" },
              ossName: { type: "string", description: "oss上的文件名" },
              remark: { type: "string", description: "备注" },
              size: { type: "number", description: "文件大小" },
              status: { type: "string", description: "上传状态" },
              uid: { type: "string", description: "uid" },
              url: { type: "string", description: "url" },
            },
          },
        },
        batteryPic: {
          type: "array",
          items: {
            additionalProperties: false,
            type: "object",
            properties: {
              name: { type: "string", description: "原始文件名" },
              ossName: { type: "string", description: "oss上的文件名" },
              remark: { type: "string", description: "备注" },
              size: { type: "number", description: "文件大小" },
              status: { type: "string", description: "上传状态" },
              uid: { type: "string", description: "uid" },
              url: { type: "string", description: "url" },
            },
          },
        },
        otherPic: {
          type: "array",
          items: {
            additionalProperties: false,
            type: "object",
            properties: {
              name: { type: "string", description: "原始文件名" },
              ossName: { type: "string", description: "oss上的文件名" },
              remark: { type: "string", description: "备注" },
              size: { type: "number", description: "文件大小" },
              status: { type: "string", description: "上传状态" },
              uid: { type: "string", description: "uid" },
              url: { type: "string", description: "url" },
            },
          },
        },
        createBy: { type: "string" },
      },
    },
  },
};
export const createVehicleResSchema = {
  additionalProperties: false,
  type: "object",
  required: [],
  properties: {
    content: {
      allOf: [
        {
          additionalProperties: false,
          type: "object",
          properties: {
            ticket: { type: "string", description: "关联的工单 id" },
            status: {
              type: "string",
              enum: ["CREATING", "FILLING", "PENDING", "PASSED"],
              description: "车辆录入工单状态",
            },
            rejected: { type: "boolean", description: "工单曾经被驳回" },
            scrapped: { type: "boolean", description: "车辆是否报废" },
            crm: { type: "string", description: "CRM 订单号" },
            terminal: { type: "string", description: "终端用户" },
            park: { type: "string", description: "车场" },
            purchaseAt: {
              tsType: "Date",
              type: "string",
              format: "date-time",
              description: "购买日期",
            },
            plateAt: {
              tsType: "Date",
              type: "string",
              format: "date-time",
              description: "上牌日期",
            },
            operateAt: {
              tsType: "Date",
              type: "string",
              format: "date-time",
              description: "运营日期",
            },
            retireAt: {
              tsType: "Date",
              type: "string",
              format: "date-time",
              description: "报废日期",
            },
            year: { type: "number", description: "年份" },
            license: {
              description: "车辆行驶证",
              type: "array",
              items: {
                additionalProperties: false,
                type: "object",
                properties: {
                  name: { type: "string", description: "原始文件名" },
                  ossName: { type: "string", description: "oss上的文件名" },
                  remark: { type: "string", description: "备注" },
                  size: { type: "number", description: "文件大小" },
                  status: { type: "string", description: "上传状态" },
                  uid: { type: "string", description: "uid" },
                  url: { type: "string", description: "url" },
                },
              },
            },
            brands: { type: "string", description: "整车品牌" },
            plate: { type: "string", description: "车牌号" },
            vin: { type: "string", description: "VIN号" },
            jobNum: { type: "string", description: "车辆工号" },
            num: { type: "string", description: "车辆自编号" },
            catl: { type: "string", description: "CATL项目名称" },
            batteryPN: { type: "string", description: "电池PN" },
            batteryNum: { type: "string", description: "电池号" },
            batteryPropRight: { type: "string", description: "电池产权" },
            power: { type: "number", description: "功率" },
            bmuHardware: { type: "string", description: "BMU硬件版本" },
            bmuSoftware: { type: "string", description: "BMU软件版本" },
            cscHardware: { type: "string", description: "CSC硬件版本" },
            cscSoftware: { type: "string", description: "CSC软件版本" },
            rdb: { type: "string", description: "RDB" },
            remark: { type: "string", description: "备注" },
            softwarePic: {
              description: "上位机软件图片",
              type: "array",
              items: {
                additionalProperties: false,
                type: "object",
                properties: {
                  name: { type: "string", description: "原始文件名" },
                  ossName: { type: "string", description: "oss上的文件名" },
                  remark: { type: "string", description: "备注" },
                  size: { type: "number", description: "文件大小" },
                  status: { type: "string", description: "上传状态" },
                  uid: { type: "string", description: "uid" },
                  url: { type: "string", description: "url" },
                },
              },
            },
            frontPic: {
              description: "正面车头图片",
              type: "array",
              items: {
                additionalProperties: false,
                type: "object",
                properties: {
                  name: { type: "string", description: "原始文件名" },
                  ossName: { type: "string", description: "oss上的文件名" },
                  remark: { type: "string", description: "备注" },
                  size: { type: "number", description: "文件大小" },
                  status: { type: "string", description: "上传状态" },
                  uid: { type: "string", description: "uid" },
                  url: { type: "string", description: "url" },
                },
              },
            },
            nameplatePic: {
              description: "车辆铭牌图片",
              type: "array",
              items: {
                additionalProperties: false,
                type: "object",
                properties: {
                  name: { type: "string", description: "原始文件名" },
                  ossName: { type: "string", description: "oss上的文件名" },
                  remark: { type: "string", description: "备注" },
                  size: { type: "number", description: "文件大小" },
                  status: { type: "string", description: "上传状态" },
                  uid: { type: "string", description: "uid" },
                  url: { type: "string", description: "url" },
                },
              },
            },
            meterPic: {
              description: "车辆仪表图片",
              type: "array",
              items: {
                additionalProperties: false,
                type: "object",
                properties: {
                  name: { type: "string", description: "原始文件名" },
                  ossName: { type: "string", description: "oss上的文件名" },
                  remark: { type: "string", description: "备注" },
                  size: { type: "number", description: "文件大小" },
                  status: { type: "string", description: "上传状态" },
                  uid: { type: "string", description: "uid" },
                  url: { type: "string", description: "url" },
                },
              },
            },
            batteryPic: {
              description: "电池号图片",
              type: "array",
              items: {
                additionalProperties: false,
                type: "object",
                properties: {
                  name: { type: "string", description: "原始文件名" },
                  ossName: { type: "string", description: "oss上的文件名" },
                  remark: { type: "string", description: "备注" },
                  size: { type: "number", description: "文件大小" },
                  status: { type: "string", description: "上传状态" },
                  uid: { type: "string", description: "uid" },
                  url: { type: "string", description: "url" },
                },
              },
            },
            otherPic: {
              description: "其他图片",
              type: "array",
              items: {
                additionalProperties: false,
                type: "object",
                properties: {
                  name: { type: "string", description: "原始文件名" },
                  ossName: { type: "string", description: "oss上的文件名" },
                  remark: { type: "string", description: "备注" },
                  size: { type: "number", description: "文件大小" },
                  status: { type: "string", description: "上传状态" },
                  uid: { type: "string", description: "uid" },
                  url: { type: "string", description: "url" },
                },
              },
            },
            createBy: { type: "string", description: "录入者" },
          },
        },
        {
          additionalProperties: false,
          type: "object",
          required: ["id"],
          properties: {
            id: { type: "string" },
            updateAt: { tsType: "Date", type: "string", format: "date-time" },
            updateBy: { type: "string" },
            createAt: { tsType: "Date", type: "string", format: "date-time" },
            createBy: { type: "string" },
          },
        },
      ],
    },
  },
};
export const listVehiclesReqSchema = {
  additionalProperties: false,
  type: "object",
  required: [],
  properties: {
    query: {
      additionalProperties: false,
      type: "object",
      required: [],
      properties: {
        _limit: {
          type: "integer",
          format: "int32",
          default: 10,
          maximum: 1000,
        },
        _offset: { type: "integer", format: "int32", default: 0 },
        _sort: { type: "string" },
        _select: { type: "array", items: { type: "string" } },
        ticket: { type: "string" },
        createAt_gte: { type: "string" },
        createAt_lte: { type: "string" },
        plate: { type: "string" },
        plate_like: { type: "string" },
        crm: { type: "string" },
        vin: { type: "string" },
        createBy: { type: "string" },
        brands: {
          oneOf: [
            { type: "string" },
            { type: "array", items: { type: "string" } },
          ],
        },
        terminal: {
          oneOf: [
            { type: "string" },
            { type: "array", items: { type: "string" } },
          ],
        },
        park: {
          oneOf: [
            { type: "string" },
            { type: "array", items: { type: "string" } },
          ],
        },
        status: {
          oneOf: [
            { type: "string", enum: ["PENDING", "PASSED", "REJECTED"] },
            {
              type: "array",
              items: {
                type: "string",
                enum: ["PENDING", "PASSED", "REJECTED"],
              },
            },
          ],
        },
      },
    },
  },
};
export const listVehiclesResSchema = {
  additionalProperties: false,
  type: "object",
  required: [],
  properties: {
    content: {
      type: "array",
      items: {
        allOf: [
          {
            additionalProperties: false,
            type: "object",
            properties: {
              ticket: { type: "string", description: "关联的工单 id" },
              status: {
                type: "string",
                enum: ["CREATING", "FILLING", "PENDING", "PASSED"],
                description: "车辆录入工单状态",
              },
              rejected: { type: "boolean", description: "工单曾经被驳回" },
              scrapped: { type: "boolean", description: "车辆是否报废" },
              crm: { type: "string", description: "CRM 订单号" },
              terminal: { type: "string", description: "终端用户" },
              park: { type: "string", description: "车场" },
              purchaseAt: {
                tsType: "Date",
                type: "string",
                format: "date-time",
                description: "购买日期",
              },
              plateAt: {
                tsType: "Date",
                type: "string",
                format: "date-time",
                description: "上牌日期",
              },
              operateAt: {
                tsType: "Date",
                type: "string",
                format: "date-time",
                description: "运营日期",
              },
              retireAt: {
                tsType: "Date",
                type: "string",
                format: "date-time",
                description: "报废日期",
              },
              year: { type: "number", description: "年份" },
              license: {
                description: "车辆行驶证",
                type: "array",
                items: {
                  additionalProperties: false,
                  type: "object",
                  properties: {
                    name: { type: "string", description: "原始文件名" },
                    ossName: { type: "string", description: "oss上的文件名" },
                    remark: { type: "string", description: "备注" },
                    size: { type: "number", description: "文件大小" },
                    status: { type: "string", description: "上传状态" },
                    uid: { type: "string", description: "uid" },
                    url: { type: "string", description: "url" },
                  },
                },
              },
              brands: { type: "string", description: "整车品牌" },
              plate: { type: "string", description: "车牌号" },
              vin: { type: "string", description: "VIN号" },
              jobNum: { type: "string", description: "车辆工号" },
              num: { type: "string", description: "车辆自编号" },
              catl: { type: "string", description: "CATL项目名称" },
              batteryPN: { type: "string", description: "电池PN" },
              batteryNum: { type: "string", description: "电池号" },
              batteryPropRight: { type: "string", description: "电池产权" },
              power: { type: "number", description: "功率" },
              bmuHardware: { type: "string", description: "BMU硬件版本" },
              bmuSoftware: { type: "string", description: "BMU软件版本" },
              cscHardware: { type: "string", description: "CSC硬件版本" },
              cscSoftware: { type: "string", description: "CSC软件版本" },
              rdb: { type: "string", description: "RDB" },
              remark: { type: "string", description: "备注" },
              softwarePic: {
                description: "上位机软件图片",
                type: "array",
                items: {
                  additionalProperties: false,
                  type: "object",
                  properties: {
                    name: { type: "string", description: "原始文件名" },
                    ossName: { type: "string", description: "oss上的文件名" },
                    remark: { type: "string", description: "备注" },
                    size: { type: "number", description: "文件大小" },
                    status: { type: "string", description: "上传状态" },
                    uid: { type: "string", description: "uid" },
                    url: { type: "string", description: "url" },
                  },
                },
              },
              frontPic: {
                description: "正面车头图片",
                type: "array",
                items: {
                  additionalProperties: false,
                  type: "object",
                  properties: {
                    name: { type: "string", description: "原始文件名" },
                    ossName: { type: "string", description: "oss上的文件名" },
                    remark: { type: "string", description: "备注" },
                    size: { type: "number", description: "文件大小" },
                    status: { type: "string", description: "上传状态" },
                    uid: { type: "string", description: "uid" },
                    url: { type: "string", description: "url" },
                  },
                },
              },
              nameplatePic: {
                description: "车辆铭牌图片",
                type: "array",
                items: {
                  additionalProperties: false,
                  type: "object",
                  properties: {
                    name: { type: "string", description: "原始文件名" },
                    ossName: { type: "string", description: "oss上的文件名" },
                    remark: { type: "string", description: "备注" },
                    size: { type: "number", description: "文件大小" },
                    status: { type: "string", description: "上传状态" },
                    uid: { type: "string", description: "uid" },
                    url: { type: "string", description: "url" },
                  },
                },
              },
              meterPic: {
                description: "车辆仪表图片",
                type: "array",
                items: {
                  additionalProperties: false,
                  type: "object",
                  properties: {
                    name: { type: "string", description: "原始文件名" },
                    ossName: { type: "string", description: "oss上的文件名" },
                    remark: { type: "string", description: "备注" },
                    size: { type: "number", description: "文件大小" },
                    status: { type: "string", description: "上传状态" },
                    uid: { type: "string", description: "uid" },
                    url: { type: "string", description: "url" },
                  },
                },
              },
              batteryPic: {
                description: "电池号图片",
                type: "array",
                items: {
                  additionalProperties: false,
                  type: "object",
                  properties: {
                    name: { type: "string", description: "原始文件名" },
                    ossName: { type: "string", description: "oss上的文件名" },
                    remark: { type: "string", description: "备注" },
                    size: { type: "number", description: "文件大小" },
                    status: { type: "string", description: "上传状态" },
                    uid: { type: "string", description: "uid" },
                    url: { type: "string", description: "url" },
                  },
                },
              },
              otherPic: {
                description: "其他图片",
                type: "array",
                items: {
                  additionalProperties: false,
                  type: "object",
                  properties: {
                    name: { type: "string", description: "原始文件名" },
                    ossName: { type: "string", description: "oss上的文件名" },
                    remark: { type: "string", description: "备注" },
                    size: { type: "number", description: "文件大小" },
                    status: { type: "string", description: "上传状态" },
                    uid: { type: "string", description: "uid" },
                    url: { type: "string", description: "url" },
                  },
                },
              },
              createBy: { type: "string", description: "录入者" },
            },
          },
          {
            additionalProperties: false,
            type: "object",
            required: ["id"],
            properties: {
              id: { type: "string" },
              updateAt: { tsType: "Date", type: "string", format: "date-time" },
              updateBy: { type: "string" },
              createAt: { tsType: "Date", type: "string", format: "date-time" },
              createBy: { type: "string" },
            },
          },
        ],
      },
    },
    headers: {
      additionalProperties: false,
      type: "object",
      required: ["X-Total-Count"],
      properties: { "X-Total-Count": { type: "integer" } },
    },
  },
};
export const getVehicleReqSchema = {
  additionalProperties: false,
  type: "object",
  required: ["vehicleId"],
  properties: { vehicleId: { type: "string" } },
};
export const getVehicleResSchema = {
  additionalProperties: false,
  type: "object",
  required: [],
  properties: {
    content: {
      allOf: [
        {
          additionalProperties: false,
          type: "object",
          properties: {
            ticket: { type: "string", description: "关联的工单 id" },
            status: {
              type: "string",
              enum: ["CREATING", "FILLING", "PENDING", "PASSED"],
              description: "车辆录入工单状态",
            },
            rejected: { type: "boolean", description: "工单曾经被驳回" },
            scrapped: { type: "boolean", description: "车辆是否报废" },
            crm: { type: "string", description: "CRM 订单号" },
            terminal: { type: "string", description: "终端用户" },
            park: { type: "string", description: "车场" },
            purchaseAt: {
              tsType: "Date",
              type: "string",
              format: "date-time",
              description: "购买日期",
            },
            plateAt: {
              tsType: "Date",
              type: "string",
              format: "date-time",
              description: "上牌日期",
            },
            operateAt: {
              tsType: "Date",
              type: "string",
              format: "date-time",
              description: "运营日期",
            },
            retireAt: {
              tsType: "Date",
              type: "string",
              format: "date-time",
              description: "报废日期",
            },
            year: { type: "number", description: "年份" },
            license: {
              description: "车辆行驶证",
              type: "array",
              items: {
                additionalProperties: false,
                type: "object",
                properties: {
                  name: { type: "string", description: "原始文件名" },
                  ossName: { type: "string", description: "oss上的文件名" },
                  remark: { type: "string", description: "备注" },
                  size: { type: "number", description: "文件大小" },
                  status: { type: "string", description: "上传状态" },
                  uid: { type: "string", description: "uid" },
                  url: { type: "string", description: "url" },
                },
              },
            },
            brands: { type: "string", description: "整车品牌" },
            plate: { type: "string", description: "车牌号" },
            vin: { type: "string", description: "VIN号" },
            jobNum: { type: "string", description: "车辆工号" },
            num: { type: "string", description: "车辆自编号" },
            catl: { type: "string", description: "CATL项目名称" },
            batteryPN: { type: "string", description: "电池PN" },
            batteryNum: { type: "string", description: "电池号" },
            batteryPropRight: { type: "string", description: "电池产权" },
            power: { type: "number", description: "功率" },
            bmuHardware: { type: "string", description: "BMU硬件版本" },
            bmuSoftware: { type: "string", description: "BMU软件版本" },
            cscHardware: { type: "string", description: "CSC硬件版本" },
            cscSoftware: { type: "string", description: "CSC软件版本" },
            rdb: { type: "string", description: "RDB" },
            remark: { type: "string", description: "备注" },
            softwarePic: {
              description: "上位机软件图片",
              type: "array",
              items: {
                additionalProperties: false,
                type: "object",
                properties: {
                  name: { type: "string", description: "原始文件名" },
                  ossName: { type: "string", description: "oss上的文件名" },
                  remark: { type: "string", description: "备注" },
                  size: { type: "number", description: "文件大小" },
                  status: { type: "string", description: "上传状态" },
                  uid: { type: "string", description: "uid" },
                  url: { type: "string", description: "url" },
                },
              },
            },
            frontPic: {
              description: "正面车头图片",
              type: "array",
              items: {
                additionalProperties: false,
                type: "object",
                properties: {
                  name: { type: "string", description: "原始文件名" },
                  ossName: { type: "string", description: "oss上的文件名" },
                  remark: { type: "string", description: "备注" },
                  size: { type: "number", description: "文件大小" },
                  status: { type: "string", description: "上传状态" },
                  uid: { type: "string", description: "uid" },
                  url: { type: "string", description: "url" },
                },
              },
            },
            nameplatePic: {
              description: "车辆铭牌图片",
              type: "array",
              items: {
                additionalProperties: false,
                type: "object",
                properties: {
                  name: { type: "string", description: "原始文件名" },
                  ossName: { type: "string", description: "oss上的文件名" },
                  remark: { type: "string", description: "备注" },
                  size: { type: "number", description: "文件大小" },
                  status: { type: "string", description: "上传状态" },
                  uid: { type: "string", description: "uid" },
                  url: { type: "string", description: "url" },
                },
              },
            },
            meterPic: {
              description: "车辆仪表图片",
              type: "array",
              items: {
                additionalProperties: false,
                type: "object",
                properties: {
                  name: { type: "string", description: "原始文件名" },
                  ossName: { type: "string", description: "oss上的文件名" },
                  remark: { type: "string", description: "备注" },
                  size: { type: "number", description: "文件大小" },
                  status: { type: "string", description: "上传状态" },
                  uid: { type: "string", description: "uid" },
                  url: { type: "string", description: "url" },
                },
              },
            },
            batteryPic: {
              description: "电池号图片",
              type: "array",
              items: {
                additionalProperties: false,
                type: "object",
                properties: {
                  name: { type: "string", description: "原始文件名" },
                  ossName: { type: "string", description: "oss上的文件名" },
                  remark: { type: "string", description: "备注" },
                  size: { type: "number", description: "文件大小" },
                  status: { type: "string", description: "上传状态" },
                  uid: { type: "string", description: "uid" },
                  url: { type: "string", description: "url" },
                },
              },
            },
            otherPic: {
              description: "其他图片",
              type: "array",
              items: {
                additionalProperties: false,
                type: "object",
                properties: {
                  name: { type: "string", description: "原始文件名" },
                  ossName: { type: "string", description: "oss上的文件名" },
                  remark: { type: "string", description: "备注" },
                  size: { type: "number", description: "文件大小" },
                  status: { type: "string", description: "上传状态" },
                  uid: { type: "string", description: "uid" },
                  url: { type: "string", description: "url" },
                },
              },
            },
            createBy: { type: "string", description: "录入者" },
          },
        },
        {
          additionalProperties: false,
          type: "object",
          required: ["id"],
          properties: {
            id: { type: "string" },
            updateAt: { tsType: "Date", type: "string", format: "date-time" },
            updateBy: { type: "string" },
            createAt: { tsType: "Date", type: "string", format: "date-time" },
            createBy: { type: "string" },
          },
        },
      ],
    },
  },
};
export const updateVehicleReqSchema = {
  additionalProperties: false,
  type: "object",
  required: ["vehicleId", "body"],
  properties: {
    vehicleId: { type: "string" },
    body: {
      additionalProperties: false,
      type: "object",
      properties: {
        ticket: { type: "string", description: "关联的工单 id" },
        status: {
          type: "string",
          enum: ["CREATING", "FILLING", "PENDING", "PASSED"],
          description: "车辆录入工单状态",
        },
        rejected: { type: "boolean", description: "工单曾经被驳回" },
        scrapped: { type: "boolean", description: "车辆是否报废" },
        crm: { type: "string", description: "CRM 订单号" },
        terminal: { type: "string", description: "终端用户" },
        park: { type: "string", description: "车场" },
        purchaseAt: {
          tsType: "Date",
          type: "string",
          format: "date-time",
          description: "购买日期",
        },
        plateAt: {
          tsType: "Date",
          type: "string",
          format: "date-time",
          description: "上牌日期",
        },
        operateAt: {
          tsType: "Date",
          type: "string",
          format: "date-time",
          description: "运营日期",
        },
        retireAt: {
          tsType: "Date",
          type: "string",
          format: "date-time",
          description: "报废日期",
        },
        year: { type: "number", description: "年份" },
        license: {
          description: "车辆行驶证",
          type: "array",
          items: {
            additionalProperties: false,
            type: "object",
            properties: {
              name: { type: "string", description: "原始文件名" },
              ossName: { type: "string", description: "oss上的文件名" },
              remark: { type: "string", description: "备注" },
              size: { type: "number", description: "文件大小" },
              status: { type: "string", description: "上传状态" },
              uid: { type: "string", description: "uid" },
              url: { type: "string", description: "url" },
            },
          },
        },
        brands: { type: "string", description: "整车品牌" },
        plate: { type: "string", description: "车牌号" },
        vin: { type: "string", description: "VIN号" },
        jobNum: { type: "string", description: "车辆工号" },
        num: { type: "string", description: "车辆自编号" },
        catl: { type: "string", description: "CATL项目名称" },
        batteryPN: { type: "string", description: "电池PN" },
        batteryNum: { type: "string", description: "电池号" },
        batteryPropRight: { type: "string", description: "电池产权" },
        power: { type: "number", description: "功率" },
        bmuHardware: { type: "string", description: "BMU硬件版本" },
        bmuSoftware: { type: "string", description: "BMU软件版本" },
        cscHardware: { type: "string", description: "CSC硬件版本" },
        cscSoftware: { type: "string", description: "CSC软件版本" },
        rdb: { type: "string", description: "RDB" },
        remark: { type: "string", description: "备注" },
        softwarePic: {
          description: "上位机软件图片",
          type: "array",
          items: {
            additionalProperties: false,
            type: "object",
            properties: {
              name: { type: "string", description: "原始文件名" },
              ossName: { type: "string", description: "oss上的文件名" },
              remark: { type: "string", description: "备注" },
              size: { type: "number", description: "文件大小" },
              status: { type: "string", description: "上传状态" },
              uid: { type: "string", description: "uid" },
              url: { type: "string", description: "url" },
            },
          },
        },
        frontPic: {
          description: "正面车头图片",
          type: "array",
          items: {
            additionalProperties: false,
            type: "object",
            properties: {
              name: { type: "string", description: "原始文件名" },
              ossName: { type: "string", description: "oss上的文件名" },
              remark: { type: "string", description: "备注" },
              size: { type: "number", description: "文件大小" },
              status: { type: "string", description: "上传状态" },
              uid: { type: "string", description: "uid" },
              url: { type: "string", description: "url" },
            },
          },
        },
        nameplatePic: {
          description: "车辆铭牌图片",
          type: "array",
          items: {
            additionalProperties: false,
            type: "object",
            properties: {
              name: { type: "string", description: "原始文件名" },
              ossName: { type: "string", description: "oss上的文件名" },
              remark: { type: "string", description: "备注" },
              size: { type: "number", description: "文件大小" },
              status: { type: "string", description: "上传状态" },
              uid: { type: "string", description: "uid" },
              url: { type: "string", description: "url" },
            },
          },
        },
        meterPic: {
          description: "车辆仪表图片",
          type: "array",
          items: {
            additionalProperties: false,
            type: "object",
            properties: {
              name: { type: "string", description: "原始文件名" },
              ossName: { type: "string", description: "oss上的文件名" },
              remark: { type: "string", description: "备注" },
              size: { type: "number", description: "文件大小" },
              status: { type: "string", description: "上传状态" },
              uid: { type: "string", description: "uid" },
              url: { type: "string", description: "url" },
            },
          },
        },
        batteryPic: {
          description: "电池号图片",
          type: "array",
          items: {
            additionalProperties: false,
            type: "object",
            properties: {
              name: { type: "string", description: "原始文件名" },
              ossName: { type: "string", description: "oss上的文件名" },
              remark: { type: "string", description: "备注" },
              size: { type: "number", description: "文件大小" },
              status: { type: "string", description: "上传状态" },
              uid: { type: "string", description: "uid" },
              url: { type: "string", description: "url" },
            },
          },
        },
        otherPic: {
          description: "其他图片",
          type: "array",
          items: {
            additionalProperties: false,
            type: "object",
            properties: {
              name: { type: "string", description: "原始文件名" },
              ossName: { type: "string", description: "oss上的文件名" },
              remark: { type: "string", description: "备注" },
              size: { type: "number", description: "文件大小" },
              status: { type: "string", description: "上传状态" },
              uid: { type: "string", description: "uid" },
              url: { type: "string", description: "url" },
            },
          },
        },
        createBy: { type: "string", description: "录入者" },
      },
    },
  },
};
export const updateVehicleResSchema = {
  additionalProperties: false,
  type: "object",
  required: [],
  properties: {
    content: {
      allOf: [
        {
          additionalProperties: false,
          type: "object",
          properties: {
            ticket: { type: "string", description: "关联的工单 id" },
            status: {
              type: "string",
              enum: ["CREATING", "FILLING", "PENDING", "PASSED"],
              description: "车辆录入工单状态",
            },
            rejected: { type: "boolean", description: "工单曾经被驳回" },
            scrapped: { type: "boolean", description: "车辆是否报废" },
            crm: { type: "string", description: "CRM 订单号" },
            terminal: { type: "string", description: "终端用户" },
            park: { type: "string", description: "车场" },
            purchaseAt: {
              tsType: "Date",
              type: "string",
              format: "date-time",
              description: "购买日期",
            },
            plateAt: {
              tsType: "Date",
              type: "string",
              format: "date-time",
              description: "上牌日期",
            },
            operateAt: {
              tsType: "Date",
              type: "string",
              format: "date-time",
              description: "运营日期",
            },
            retireAt: {
              tsType: "Date",
              type: "string",
              format: "date-time",
              description: "报废日期",
            },
            year: { type: "number", description: "年份" },
            license: {
              description: "车辆行驶证",
              type: "array",
              items: {
                additionalProperties: false,
                type: "object",
                properties: {
                  name: { type: "string", description: "原始文件名" },
                  ossName: { type: "string", description: "oss上的文件名" },
                  remark: { type: "string", description: "备注" },
                  size: { type: "number", description: "文件大小" },
                  status: { type: "string", description: "上传状态" },
                  uid: { type: "string", description: "uid" },
                  url: { type: "string", description: "url" },
                },
              },
            },
            brands: { type: "string", description: "整车品牌" },
            plate: { type: "string", description: "车牌号" },
            vin: { type: "string", description: "VIN号" },
            jobNum: { type: "string", description: "车辆工号" },
            num: { type: "string", description: "车辆自编号" },
            catl: { type: "string", description: "CATL项目名称" },
            batteryPN: { type: "string", description: "电池PN" },
            batteryNum: { type: "string", description: "电池号" },
            batteryPropRight: { type: "string", description: "电池产权" },
            power: { type: "number", description: "功率" },
            bmuHardware: { type: "string", description: "BMU硬件版本" },
            bmuSoftware: { type: "string", description: "BMU软件版本" },
            cscHardware: { type: "string", description: "CSC硬件版本" },
            cscSoftware: { type: "string", description: "CSC软件版本" },
            rdb: { type: "string", description: "RDB" },
            remark: { type: "string", description: "备注" },
            softwarePic: {
              description: "上位机软件图片",
              type: "array",
              items: {
                additionalProperties: false,
                type: "object",
                properties: {
                  name: { type: "string", description: "原始文件名" },
                  ossName: { type: "string", description: "oss上的文件名" },
                  remark: { type: "string", description: "备注" },
                  size: { type: "number", description: "文件大小" },
                  status: { type: "string", description: "上传状态" },
                  uid: { type: "string", description: "uid" },
                  url: { type: "string", description: "url" },
                },
              },
            },
            frontPic: {
              description: "正面车头图片",
              type: "array",
              items: {
                additionalProperties: false,
                type: "object",
                properties: {
                  name: { type: "string", description: "原始文件名" },
                  ossName: { type: "string", description: "oss上的文件名" },
                  remark: { type: "string", description: "备注" },
                  size: { type: "number", description: "文件大小" },
                  status: { type: "string", description: "上传状态" },
                  uid: { type: "string", description: "uid" },
                  url: { type: "string", description: "url" },
                },
              },
            },
            nameplatePic: {
              description: "车辆铭牌图片",
              type: "array",
              items: {
                additionalProperties: false,
                type: "object",
                properties: {
                  name: { type: "string", description: "原始文件名" },
                  ossName: { type: "string", description: "oss上的文件名" },
                  remark: { type: "string", description: "备注" },
                  size: { type: "number", description: "文件大小" },
                  status: { type: "string", description: "上传状态" },
                  uid: { type: "string", description: "uid" },
                  url: { type: "string", description: "url" },
                },
              },
            },
            meterPic: {
              description: "车辆仪表图片",
              type: "array",
              items: {
                additionalProperties: false,
                type: "object",
                properties: {
                  name: { type: "string", description: "原始文件名" },
                  ossName: { type: "string", description: "oss上的文件名" },
                  remark: { type: "string", description: "备注" },
                  size: { type: "number", description: "文件大小" },
                  status: { type: "string", description: "上传状态" },
                  uid: { type: "string", description: "uid" },
                  url: { type: "string", description: "url" },
                },
              },
            },
            batteryPic: {
              description: "电池号图片",
              type: "array",
              items: {
                additionalProperties: false,
                type: "object",
                properties: {
                  name: { type: "string", description: "原始文件名" },
                  ossName: { type: "string", description: "oss上的文件名" },
                  remark: { type: "string", description: "备注" },
                  size: { type: "number", description: "文件大小" },
                  status: { type: "string", description: "上传状态" },
                  uid: { type: "string", description: "uid" },
                  url: { type: "string", description: "url" },
                },
              },
            },
            otherPic: {
              description: "其他图片",
              type: "array",
              items: {
                additionalProperties: false,
                type: "object",
                properties: {
                  name: { type: "string", description: "原始文件名" },
                  ossName: { type: "string", description: "oss上的文件名" },
                  remark: { type: "string", description: "备注" },
                  size: { type: "number", description: "文件大小" },
                  status: { type: "string", description: "上传状态" },
                  uid: { type: "string", description: "uid" },
                  url: { type: "string", description: "url" },
                },
              },
            },
            createBy: { type: "string", description: "录入者" },
          },
        },
        {
          additionalProperties: false,
          type: "object",
          required: ["id"],
          properties: {
            id: { type: "string" },
            updateAt: { tsType: "Date", type: "string", format: "date-time" },
            updateBy: { type: "string" },
            createAt: { tsType: "Date", type: "string", format: "date-time" },
            createBy: { type: "string" },
          },
        },
      ],
    },
  },
};
export const deleteVehicleReqSchema = {
  additionalProperties: false,
  type: "object",
  required: ["vehicleId"],
  properties: { vehicleId: { type: "string" } },
};
export const listVehicleAlertsReqSchema = {
  additionalProperties: false,
  type: "object",
  required: ["vehicleId"],
  properties: {
    query: {
      additionalProperties: false,
      type: "object",
      required: [],
      properties: {
        _limit: {
          type: "integer",
          format: "int32",
          default: 10,
          maximum: 1000,
        },
        _offset: { type: "integer", format: "int32", default: 0 },
        _sort: { type: "string" },
        _select: { type: "array", items: { type: "string" } },
        level: {
          oneOf: [
            {
              type: "array",
              items: { type: "integer", format: "int32", minLength: 1 },
            },
            { type: "integer", format: "int32", minLength: 1 },
          ],
        },
      },
    },
    vehicleId: { type: "string" },
  },
};
export const listVehicleAlertsResSchema = {
  additionalProperties: false,
  type: "object",
  required: [],
  properties: {
    content: {
      type: "array",
      items: {
        allOf: [
          {
            additionalProperties: false,
            type: "object",
            properties: {
              level: {
                type: "integer",
                format: "int32",
                description: "故障等级",
              },
              code: { type: "string", description: "故障码" },
              name: { type: "string", description: "故障名称" },
              startedAt: {
                tsType: "Date",
                type: "string",
                format: "date-time",
                description: "开始报警的时间",
              },
              count: { type: "integer", format: "int32", description: "次数" },
            },
          },
          {
            additionalProperties: false,
            type: "object",
            required: ["id"],
            properties: {
              id: { type: "string" },
              updateAt: { tsType: "Date", type: "string", format: "date-time" },
              updateBy: { type: "string" },
              createAt: { tsType: "Date", type: "string", format: "date-time" },
              createBy: { type: "string" },
            },
          },
        ],
      },
    },
    headers: {
      additionalProperties: false,
      type: "object",
      required: ["X-Total-Count"],
      properties: { "X-Total-Count": { type: "integer" } },
    },
  },
};
